parsers:
  sportbox:
    domain: "https://news.sportbox.ru"
    path: "/Vidy_sporta/Futbol/Russia/1st_division"
  onefnl:
    domain: "https://1fnl.ru"
    path: "/news/"
  sportsru:
    domain: "https://www.sports.ru"
    path: "/fnl/"